name: Angular Module CI

on:
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'frontend/**'
      - '.github/workflows/angular.yml'

jobs:
  build-and-test:
    name: Run Angular pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '>=24.11.0'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install Node.js dependencies
        run: npm install
        working-directory: ./frontend

      - name: Run Angular tests
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless
        working-directory: ./frontend